services:
  notes-api:
    image: notes-api
    build:
      context: .
      dockerfile: NotesApi/Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    ports:
      - 3000:3000
    environment:
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - Sns_LocalMode=true
      - Localstack_SnsServiceUrl=http://localstack:4566
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    links:
      - dynamodb-database

  notes-api-test:
    image: notes-api-test
    build:
      context: .
      dockerfile: NotesApi.Tests/Dockerfile
      args:
        - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
        - SONAR_TOKEN=${SONAR_TOKEN}
    environment:
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - Sns_LocalMode=true
      - Localstack_SnsServiceUrl=http://localstack:4566
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    links:
      - dynamodb-database
      - localstack

  dynamodb-database:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb"
    ports:
      - 8000:8000

  localstack:
    image: localstack/localstack:0.14.1  
    hostname: awslocal    
    ports:
      - "4566:4566"      
    environment:
      - SERVICES=sns,sqs
      - DEBUG=1                  
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack      
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
