version: "3.2"

services:
  notes-api:
    image: notes-api
    build:
      context: NotesApi/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    links:
      - dynamodb-database

  notes-api-test:
    image: notes-api-test
    build:
      context: .
      dockerfile: NotesApi.Tests/Dockerfile
    environment:
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    links:
      - dynamodb-database
  dynamodb-database:
    container_name: dynamodb
    image: amazon/dynamodb-local:latest
    entrypoint: java
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    restart: always    
    ports:
      - "8000:8000"